services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    command: ['start-dev','--import-realm']
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:8080"