GRPC localhost:9000/CardService/CreateCard
Content-Type: application/json

{
  "userId": 1,
  "cardNumber": 9239999999123418,
  "cardHolderFullName": "John Doe TEsstst",
  "expiryDate": "2026-05-23",
  "balanceAmount": -3,
  "cardStatus": "ACTIVE"
}