GRPC localhost:9000/CardService/CreateCard
Content-Type: application/json

{
  "userId": 1,
  "cardNumber": 9259907899125438,
  "cardHolderFullName": "John Doe TEsstst",
  "expiryDate": "2026-05-23",
  "balanceAmount": 3,
  "cardStatus": "ACTIVE"
}