GRPC localhost:9000/CardService/CreateCard
Content-Type: application/json

{
  "userId": 2,
  "cardNumber": 1111111111111117,
  "cardHolderFullName": "John Doe Merrel",
  "expiryDate": "2026-05-23",
  "balanceAmount": 5,
  "cardStatus": "ACTIVE"
}