spring.application.name=user-service
server.port=4004
realm=cardManagement


OAUTH2_SERVER_URL=http://localhost:9191
REALM_URL=${OAUTH2_SERVER_URL}/realms/cardManagement

spring.security.oauth2.resourceserver.jwt.issuer-uri=${REALM_URL}
spring.security.oauth2.client.registration.cardManagement.client-id=card-management
spring.security.oauth2.client.registration.cardManagement.client-secret=XlUOGRQmlpcaOamrgU6LoSioP2HHOX3s
spring.security.oauth2.client.registration.cardManagement.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.cardManagement.scope=openid, profile
spring.security.oauth2.client.registration.cardManagement.redirect-uri={baseUrl}/login/oauth2/code/cardManagement
spring.security.oauth2.client.registration.cardManagement.provider=keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=${REALM_URL}

jwt.auth.converter.principle-attribute=email
jwt.auth.converter.resource-id=card-management
