spring.application.name=card-service
spring.datasource.url=jdbc:postgresql://localhost:5432/card_service
spring.datasource.username=postgres
spring.datasource.password=mint2024
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

application.security.card.secret-key=T5bLsc/gYtQdyErg8/r4VQ==
application.security.card.encryption-cipher="AES"

server.port=4000
grpc.server.port=9000
spring.kafka.bootstrap-servers=localhost:9092

